### ISSUE TITLE
Add more filters

### ISSUE THREAD

**Issue by SparshBohra** [SparshBohra/Image-Filters#1]
### Description
Applying grayscale, blur, reflection, edge detection filters to bitmap images in C. You can help by adding more filters like sepia, negative etc. Short and simple.

### Tasks
- [ ] Edit the filter.c file by adding additional filters to the char pointer and add more switch cases
- [ ] Write the function for the filter in helpers.c
- [ ] Lastly, add the filter to the helpers.h header file

**Comment by burkesk** [comment]
Hello! I want to contribute to this project as my first issue. And i have already made some changes. Now i am gonna send a pull request and hope to contribute more. 
Good day :)
